# Generated by Django 4.0 on 2022-01-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcard.subject'),
            preserve_default=False,
        ),
    ]
