# Generated by Django 4.0 on 2022-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_subject_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
