# Generated by Django 4.0 on 2022-01-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flashcard', '0004_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
