# Generated by Django 4.0 on 2022-02-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_alter_question_subject_alter_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_ref',
        ),
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='CardType',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.cardtype'),
        ),
        migrations.AddField(
            model_name='answer',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.card'),
        ),
    ]
